//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteDuo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_es {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_es() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClienteDuo.Properties.Resources.es", typeof(Resources_es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        public static string BtnAccept {
            get {
                return ResourceManager.GetString("BtnAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir Amigo.
        /// </summary>
        public static string BtnAddFriend {
            get {
                return ResourceManager.GetString("BtnAddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios Bloqueados.
        /// </summary>
        public static string BtnBlockedUsers {
            get {
                return ResourceManager.GetString("BtnBlockedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloquear.
        /// </summary>
        public static string BtnBlockUser {
            get {
                return ResourceManager.GetString("BtnBlockUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar Contraseña.
        /// </summary>
        public static string BtnChangePassword {
            get {
                return ResourceManager.GetString("BtnChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuar.
        /// </summary>
        public static string BtnContinue {
            get {
                return ResourceManager.GetString("BtnContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir de la Sala.
        /// </summary>
        public static string BtnExitLobby {
            get {
                return ResourceManager.GetString("BtnExitLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitudes de Amistad.
        /// </summary>
        public static string BtnFriendRequests {
            get {
                return ResourceManager.GetString("BtnFriendRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unirse.
        /// </summary>
        public static string BtnJoin {
            get {
                return ResourceManager.GetString("BtnJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar Como Invitado.
        /// </summary>
        public static string BtnJoinAsGuest {
            get {
                return ResourceManager.GetString("BtnJoinAsGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar a una Partida.
        /// </summary>
        public static string BtnJoinParty {
            get {
                return ResourceManager.GetString("BtnJoinParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expulsar.
        /// </summary>
        public static string BtnKick {
            get {
                return ResourceManager.GetString("BtnKick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Sesión.
        /// </summary>
        public static string BtnLogin {
            get {
                return ResourceManager.GetString("BtnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar Sesión.
        /// </summary>
        public static string BtnLogOut {
            get {
                return ResourceManager.GetString("BtnLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Perfil.
        /// </summary>
        public static string BtnModifyProfile {
            get {
                return ResourceManager.GetString("BtnModifyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Cuenta.
        /// </summary>
        public static string BtnNewAccount {
            get {
                return ResourceManager.GetString("BtnNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Partida.
        /// </summary>
        public static string BtnNewParty {
            get {
                return ResourceManager.GetString("BtnNewParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        public static string BtnProfile {
            get {
                return ResourceManager.GetString("BtnProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir del juego.
        /// </summary>
        public static string BtnQuitGame {
            get {
                return ResourceManager.GetString("BtnQuitGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechazar.
        /// </summary>
        public static string BtnReject {
            get {
                return ResourceManager.GetString("BtnReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Partida.
        /// </summary>
        public static string BtnStartGame {
            get {
                return ResourceManager.GetString("BtnStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desbloquear.
        /// </summary>
        public static string BtnUnblockUser {
            get {
                return ResourceManager.GetString("BtnUnblockUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Amigo.
        /// </summary>
        public static string BtnUnfriend {
            get {
                return ResourceManager.GetString("BtnUnfriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya eres amigo del este usuario.
        /// </summary>
        public static string DlgAlreadyFriends {
            get {
                return ResourceManager.GetString("DlgAlreadyFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Estás seguro de que deseas bloqueas a este usuario? No podrás ingresar a ninguna partida donde este este jugador ni el podrá ingresar a la tuya, tampoco lo podrás agregar como amigo, ni el a ti..
        /// </summary>
        public static string DlgBlockConfirmation {
            get {
                return ResourceManager.GetString("DlgBlockConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario ha sido bloqueado.
        /// </summary>
        public static string DlgBlockedUser {
            get {
                return ResourceManager.GetString("DlgBlockedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error al conectarse con el servicio, inténtelo de nuevo más tarde.
        /// </summary>
        public static string DlgConnectionError {
            get {
                return ResourceManager.GetString("DlgConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo electrónico debe tener menos de 30 caracteres y un formato valido (----@dominio.com).
        /// </summary>
        public static string DlgEmailInvalid {
            get {
                return ResourceManager.GetString("DlgEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El email ingresado no está asociado a ninguna cuenta.
        /// </summary>
        public static string DlgEmailNonExistent {
            get {
                return ResourceManager.GetString("DlgEmailNonExistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Una cuenta con ese correo electrónico ya se encuentra registrada.
        /// </summary>
        public static string DlgEmailTaken {
            get {
                return ResourceManager.GetString("DlgEmailTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos los campos deben estar llenos antes de continuar.
        /// </summary>
        public static string DlgEmptyFields {
            get {
                return ResourceManager.GetString("DlgEmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo expulsar este usuario, por favor defina una razón de expulsión.
        /// </summary>
        public static string DlgEmptyKickingReason {
            get {
                return ResourceManager.GetString("DlgEmptyKickingReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro de que desea abandonar la partida? No podrá unirse hasta que esta termine.
        /// </summary>
        public static string DlgExitConfirmation {
            get {
                return ResourceManager.GetString("DlgExitConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro de que desea abandonar la partida? No podrá volver a unirse.
        /// </summary>
        public static string DlgExitMatchConfirmation {
            get {
                return ResourceManager.GetString("DlgExitMatchConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario o contraseña incorrectos.
        /// </summary>
        public static string DlgFailedLogin {
            get {
                return ResourceManager.GetString("DlgFailedLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Una solicitud de amistad ya se ha enviado anteriormente.
        /// </summary>
        public static string DlgFriendRequestAlreadySent {
            get {
                return ResourceManager.GetString("DlgFriendRequestAlreadySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haz eliminado la solicitud.
        /// </summary>
        public static string DlgFriendRequestDeleted {
            get {
                return ResourceManager.GetString("DlgFriendRequestDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error al enviar la solicitud de amistar a este usuario.
        /// </summary>
        public static string DlgFriendRequestError {
            get {
                return ResourceManager.GetString("DlgFriendRequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud de amistad enviada.
        /// </summary>
        public static string DlgFriendRequestSent {
            get {
                return ResourceManager.GetString("DlgFriendRequestSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puedes mandar una solicitud a ti mismo.
        /// </summary>
        public static string DlgFriendYourself {
            get {
                return ResourceManager.GetString("DlgFriendYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La partida ya está llena, inténtalo de nuevo más tarde.
        /// </summary>
        public static string DlgFullParty {
            get {
                return ResourceManager.GetString("DlgFullParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El host a abandonado la partida.
        /// </summary>
        public static string DlgHostHasClosedTheParty {
            get {
                return ResourceManager.GetString("DlgHostHasClosedTheParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña debe contener al menos: 8 caracteres, un símbolo especial(!@?#$&amp;$°¬|/%*), una letra mayúscula y minúscula, y un máximo de 16 caracteres.
        /// </summary>
        public static string DlgInsecurePassword {
            get {
                return ResourceManager.GetString("DlgInsecurePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato inválido.
        /// </summary>
        public static string DlgInvalidFormat {
            get {
                return ResourceManager.GetString("DlgInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código de partida debe ser un numero con máximo 4 dígitos.
        /// </summary>
        public static string DlgInvalidPartyCodeFormat {
            get {
                return ResourceManager.GetString("DlgInvalidPartyCodeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to está en línea.
        /// </summary>
        public static string DlgIsNowActive {
            get {
                return ResourceManager.GetString("DlgIsNowActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha sido expulsado de la partida. .
        /// </summary>
        public static string DlgKickedPlayer {
            get {
                return ResourceManager.GetString("DlgKickedPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El motivo de su expulsión es: .
        /// </summary>
        public static string DlgKickingReason {
            get {
                return ResourceManager.GetString("DlgKickingReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Estás seguro de que deseas cerrar esta sesión?.
        /// </summary>
        public static string DlgLogOutConfirmation {
            get {
                return ResourceManager.GetString("DlgLogOutConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un mensaje solo puede contener 250 caracteres.
        /// </summary>
        public static string DlgMessageMaxCharacters {
            get {
                return ResourceManager.GetString("DlgMessageMaxCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha registrado el usuario correctamente.
        /// </summary>
        public static string DlgNewAccountSuccess {
            get {
                return ResourceManager.GetString("DlgNewAccountSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo iniciar la partida, el lobby debe tener al menos 2 jugadores.
        /// </summary>
        public static string DlgNotEnoughPlayers {
            get {
                return ResourceManager.GetString("DlgNotEnoughPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Ahora son amigos!.
        /// </summary>
        public static string DlgNowFriends {
            get {
                return ResourceManager.GetString("DlgNowFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código de partida no es correcto.
        /// </summary>
        public static string DlgPartyNotFound {
            get {
                return ResourceManager.GetString("DlgPartyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña y confirmación de contraseña deben coincidir.
        /// </summary>
        public static string DlgPasswordDoesNotMatch {
            get {
                return ResourceManager.GetString("DlgPasswordDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu foto de perfil se ha actualizado.
        /// </summary>
        public static string DlgProfilePictureUpdated {
            get {
                return ResourceManager.GetString("DlgProfilePictureUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error con el servicio, inténtelo de nuevo más tarde.
        /// </summary>
        public static string DlgServiceException {
            get {
                return ResourceManager.GetString("DlgServiceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario desbloqueado satisfactoriamente.
        /// </summary>
        public static string DlgUnblockSuccess {
            get {
                return ResourceManager.GetString("DlgUnblockSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya no son amigos.
        /// </summary>
        public static string DlgUnfriend {
            get {
                return ResourceManager.GetString("DlgUnfriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Estás seguro que deseas eliminar a este usuario de tus amigos?.
        /// </summary>
        public static string DlgUnfriendConfirmation {
            get {
                return ResourceManager.GetString("DlgUnfriendConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Una sesión ya está activa.
        /// </summary>
        public static string DlgUserAlreadyLoggedIn {
            get {
                return ResourceManager.GetString("DlgUserAlreadyLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puedes entrar a esta partida, un usuario que has bloqueado o te tiene bloqueado esta en la partida.
        /// </summary>
        public static string DlgUserBlockedInParty {
            get {
                return ResourceManager.GetString("DlgUserBlockedInParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de usuario no existe.
        /// </summary>
        public static string DlgUsernameDoesNotExist {
            get {
                return ResourceManager.GetString("DlgUsernameDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de usuario debe contener solo caracteres alfanuméricos, al menos 3 caracteres, un máximo de 14 y no contener la palabra &quot;guest&quot;.
        /// </summary>
        public static string DlgUsernameInvalid {
            get {
                return ResourceManager.GetString("DlgUsernameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El máximo de caracteres para el nombre de usuario es de 30.
        /// </summary>
        public static string DlgUsernameMaxCharacters {
            get {
                return ResourceManager.GetString("DlgUsernameMaxCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe ese nombre de usuario.
        /// </summary>
        public static string DlgUsernameTaken {
            get {
                return ResourceManager.GetString("DlgUsernameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código incorrecto.
        /// </summary>
        public static string DlgWrongCode {
            get {
                return ResourceManager.GetString("DlgWrongCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir amigo.
        /// </summary>
        public static string LblAddNewFriend {
            get {
                return ResourceManager.GetString("LblAddNewFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculando resultados....
        /// </summary>
        public static string LblCalculatingResults {
            get {
                return ResourceManager.GetString("LblCalculatingResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartas restantes.
        /// </summary>
        public static string LblCardsLeft {
            get {
                return ResourceManager.GetString("LblCardsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string LblChat {
            get {
                return ResourceManager.GetString("LblChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string LblCode {
            get {
                return ResourceManager.GetString("LblCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar Nueva Contraseña.
        /// </summary>
        public static string LblConfirmNewPassword {
            get {
                return ResourceManager.GetString("LblConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar Contraseña.
        /// </summary>
        public static string LblConfirmPassword {
            get {
                return ResourceManager.GetString("LblConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo Electrónico.
        /// </summary>
        public static string LblEmail {
            get {
                return ResourceManager.GetString("LblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amigos.
        /// </summary>
        public static string LblFriends {
            get {
                return ResourceManager.GetString("LblFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración del Juego.
        /// </summary>
        public static string LblGameSettings {
            get {
                return ResourceManager.GetString("LblGameSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Te enviaremos un correo para restablecer tu contraseña.
        /// </summary>
        public static string LblInfoResetPassword {
            get {
                return ResourceManager.GetString("LblInfoResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de Usuario Temporal.
        /// </summary>
        public static string LblInGameUsername {
            get {
                return ResourceManager.GetString("LblInGameUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puntuaciones.
        /// </summary>
        public static string LblLeaderboard {
            get {
                return ResourceManager.GetString("LblLeaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fin de partida.
        /// </summary>
        public static string LblMatchEnd {
            get {
                return ResourceManager.GetString("LblMatchEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi Perfil.
        /// </summary>
        public static string LblMyProfile {
            get {
                return ResourceManager.GetString("LblMyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Contraseña.
        /// </summary>
        public static string LblNewPassword {
            get {
                return ResourceManager.GetString("LblNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de Partida.
        /// </summary>
        public static string LblPartyCode {
            get {
                return ResourceManager.GetString("LblPartyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string LblPassword {
            get {
                return ResourceManager.GetString("LblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olvidé mi contraseña.
        /// </summary>
        public static string LblPasswordForgotten {
            get {
                return ResourceManager.GetString("LblPasswordForgotten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jugadores.
        /// </summary>
        public static string LblPlayers {
            get {
                return ResourceManager.GetString("LblPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listo.
        /// </summary>
        public static string LblReady {
            get {
                return ResourceManager.GetString("LblReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elija un motivo (Opcional).
        /// </summary>
        public static string LblSelectReason {
            get {
                return ResourceManager.GetString("LblSelectReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juegos Ganados.
        /// </summary>
        public static string LblTotalWins {
            get {
                return ResourceManager.GetString("LblTotalWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trofeos.
        /// </summary>
        public static string LblTrophies {
            get {
                return ResourceManager.GetString("LblTrophies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de Usuario.
        /// </summary>
        public static string LblUsername {
            get {
                return ResourceManager.GetString("LblUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ganador.
        /// </summary>
        public static string LblWinner {
            get {
                return ResourceManager.GetString("LblWinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trampa.
        /// </summary>
        public static string RsnCheating {
            get {
                return ResourceManager.GetString("RsnCheating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comportamiento inadecuado.
        /// </summary>
        public static string RsnInappropriateBehaviour {
            get {
                return ResourceManager.GetString("RsnInappropriateBehaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spam.
        /// </summary>
        public static string RsnSpam {
            get {
                return ResourceManager.GetString("RsnSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerta.
        /// </summary>
        public static string TitleAlert {
            get {
                return ResourceManager.GetString("TitleAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expulsar jugador.
        /// </summary>
        public static string TitleKickPlayer {
            get {
                return ResourceManager.GetString("TitleKickPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher.
        /// </summary>
        public static string TitleLauncher {
            get {
                return ResourceManager.GetString("TitleLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Sesión.
        /// </summary>
        public static string TitleLogin {
            get {
                return ResourceManager.GetString("TitleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Cuenta.
        /// </summary>
        public static string TitleNewAccount {
            get {
                return ResourceManager.GetString("TitleNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reestablecer Contraseña.
        /// </summary>
        public static string TitlePasswordReset {
            get {
                return ResourceManager.GetString("TitlePasswordReset", resourceCulture);
            }
        }
    }
}
