//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteDuo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClienteDuo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Friend.
        /// </summary>
        public static string BtnAddFriend {
            get {
                return ResourceManager.GetString("BtnAddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string BtnContinue {
            get {
                return ResourceManager.GetString("BtnContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Lobby.
        /// </summary>
        public static string BtnExitLobby {
            get {
                return ResourceManager.GetString("BtnExitLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        public static string BtnJoin {
            get {
                return ResourceManager.GetString("BtnJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join As Guest.
        /// </summary>
        public static string BtnJoinAsGuest {
            get {
                return ResourceManager.GetString("BtnJoinAsGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Party.
        /// </summary>
        public static string BtnJoinParty {
            get {
                return ResourceManager.GetString("BtnJoinParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string BtnLogin {
            get {
                return ResourceManager.GetString("BtnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Account.
        /// </summary>
        public static string BtnNewAccount {
            get {
                return ResourceManager.GetString("BtnNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Party.
        /// </summary>
        public static string BtnNewParty {
            get {
                return ResourceManager.GetString("BtnNewParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit Game.
        /// </summary>
        public static string BtnQuitGame {
            get {
                return ResourceManager.GetString("BtnQuitGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Game.
        /// </summary>
        public static string BtnStartGame {
            get {
                return ResourceManager.GetString("BtnStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error connecting with the service, try again later.
        /// </summary>
        public static string DlgConnectionError {
            get {
                return ResourceManager.GetString("DlgConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max characters for email is 30.
        /// </summary>
        public static string DlgEmailMaxCharacters {
            get {
                return ResourceManager.GetString("DlgEmailMaxCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An account with that email is already registered.
        /// </summary>
        public static string DlgEmailTaken {
            get {
                return ResourceManager.GetString("DlgEmailTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields must be completed.
        /// </summary>
        public static string DlgEmptyFields {
            get {
                return ResourceManager.GetString("DlgEmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect email or password.
        /// </summary>
        public static string DlgFailedLogin {
            get {
                return ResourceManager.GetString("DlgFailedLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The party is full already, try again later.
        /// </summary>
        public static string DlgFullParty {
            get {
                return ResourceManager.GetString("DlgFullParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password needs to contain at least: 8 characters, one special symbol, one uppercase and lowercase letter.
        /// </summary>
        public static string DlgInsecurePassword {
            get {
                return ResourceManager.GetString("DlgInsecurePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party code needs to be a number with a max of 4 digits.
        /// </summary>
        public static string DlgInvalidPartyCodeFormat {
            get {
                return ResourceManager.GetString("DlgInvalidPartyCodeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A message can only contain 250 characters.
        /// </summary>
        public static string DlgMessageMaxCharacters {
            get {
                return ResourceManager.GetString("DlgMessageMaxCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need a minimum of 2 players to start the game.
        /// </summary>
        public static string DlgMinPlayers {
            get {
                return ResourceManager.GetString("DlgMinPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user has been registered succesfully.
        /// </summary>
        public static string DlgNewAccountSuccess {
            get {
                return ResourceManager.GetString("DlgNewAccountSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The party code is incorrect.
        /// </summary>
        public static string DlgPartyNotFound {
            get {
                return ResourceManager.GetString("DlgPartyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error connecting with the service, try again later.
        /// </summary>
        public static string DlgServiceException {
            get {
                return ResourceManager.GetString("DlgServiceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max characters for username is 30.
        /// </summary>
        public static string DlgUsernameMaxCharacters {
            get {
                return ResourceManager.GetString("DlgUsernameMaxCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is already taken.
        /// </summary>
        public static string DlgUsernameTaken {
            get {
                return ResourceManager.GetString("DlgUsernameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string LblChat {
            get {
                return ResourceManager.GetString("LblChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string LblConfirmPassword {
            get {
                return ResourceManager.GetString("LblConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string LblEmail {
            get {
                return ResourceManager.GetString("LblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string LblFriends {
            get {
                return ResourceManager.GetString("LblFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Settings.
        /// </summary>
        public static string LblGameSettings {
            get {
                return ResourceManager.GetString("LblGameSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary Username.
        /// </summary>
        public static string LblInGameUsername {
            get {
                return ResourceManager.GetString("LblInGameUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaderboard.
        /// </summary>
        public static string LblLeaderboard {
            get {
                return ResourceManager.GetString("LblLeaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string LblMyProfile {
            get {
                return ResourceManager.GetString("LblMyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Code.
        /// </summary>
        public static string LblPartyCode {
            get {
                return ResourceManager.GetString("LblPartyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LblPassword {
            get {
                return ResourceManager.GetString("LblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        public static string LblPlayers {
            get {
                return ResourceManager.GetString("LblPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string LblUsername {
            get {
                return ResourceManager.GetString("LblUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        public static string TitleAlert {
            get {
                return ResourceManager.GetString("TitleAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Party.
        /// </summary>
        public static string TitleJoinParty {
            get {
                return ResourceManager.GetString("TitleJoinParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher.
        /// </summary>
        public static string TItleLauncher {
            get {
                return ResourceManager.GetString("TItleLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string TitleLogin {
            get {
                return ResourceManager.GetString("TitleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Account.
        /// </summary>
        public static string TitleNewAccount {
            get {
                return ResourceManager.GetString("TitleNewAccount", resourceCulture);
            }
        }
    }
}
