//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteDuo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_fr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClienteDuo.Properties.Resources.fr", typeof(Resources_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuer.
        /// </summary>
        public static string BtnContinue {
            get {
                return ResourceManager.GetString("BtnContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sortir.
        /// </summary>
        public static string BtnExitLobby {
            get {
                return ResourceManager.GetString("BtnExitLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejoindre.
        /// </summary>
        public static string BtnJoin {
            get {
                return ResourceManager.GetString("BtnJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejoindre comme invité.
        /// </summary>
        public static string BtnJoinAsGuest {
            get {
                return ResourceManager.GetString("BtnJoinAsGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejoindre groupe.
        /// </summary>
        public static string BtnJoinParty {
            get {
                return ResourceManager.GetString("BtnJoinParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejoindre.
        /// </summary>
        public static string BtnLogin {
            get {
                return ResourceManager.GetString("BtnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouvelle compte.
        /// </summary>
        public static string BtnNewAccount {
            get {
                return ResourceManager.GetString("BtnNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouvel groupe.
        /// </summary>
        public static string BtnNewParty {
            get {
                return ResourceManager.GetString("BtnNewParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sortir.
        /// </summary>
        public static string BtnQuitGame {
            get {
                return ResourceManager.GetString("BtnQuitGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commencer partie.
        /// </summary>
        public static string BtnStartGame {
            get {
                return ResourceManager.GetString("BtnStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il y avait un échec de connection avec le service, essayer autre fois à plus tard.
        /// </summary>
        public static string DlgConnectionError {
            get {
                return ResourceManager.GetString("DlgConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An account with that email is already registered.
        /// </summary>
        public static string DlgEmailTaken {
            get {
                return ResourceManager.GetString("DlgEmailTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tous les champes doivent être remplis.
        /// </summary>
        public static string DlgEmptyFields {
            get {
                return ResourceManager.GetString("DlgEmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Étes vous sur de sortir du jeu? Vous ne pourrez rentrer jusqu&apos;a il est fini.
        /// </summary>
        public static string DlgExitConfirmation {
            get {
                return ResourceManager.GetString("DlgExitConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Etes vous sur de sortir du jeu? Vous ne pourrez rentrer autres fois.
        /// </summary>
        public static string DlgExitMatchConfirmation {
            get {
                return ResourceManager.GetString("DlgExitMatchConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom d&apos;utilisateur ou courriel incorrectes.
        /// </summary>
        public static string DlgFailedLogin {
            get {
                return ResourceManager.GetString("DlgFailedLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le groupe est rempli, réessayer à plus tard.
        /// </summary>
        public static string DlgFullParty {
            get {
                return ResourceManager.GetString("DlgFullParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La mot de passe dois contenir au moins: 8 caractères, un caractèr spéciaux, et des lettres majuscules et minuscules.
        /// </summary>
        public static string DlgInsecurePassword {
            get {
                return ResourceManager.GetString("DlgInsecurePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le code de groupe doit être un numéro de 4 chiffres comme maximum.
        /// </summary>
        public static string DlgInvalidPartyCodeFormat {
            get {
                return ResourceManager.GetString("DlgInvalidPartyCodeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Des messages peuvent contenir seulement 250 caractères.
        /// </summary>
        public static string DlgMessageMaxCharacters {
            get {
                return ResourceManager.GetString("DlgMessageMaxCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom d&apos;utilisater est enregistré avec succès.
        /// </summary>
        public static string DlgNewAccountSuccess {
            get {
                return ResourceManager.GetString("DlgNewAccountSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le code de groupe est incorrecte.
        /// </summary>
        public static string DlgPartyNotFound {
            get {
                return ResourceManager.GetString("DlgPartyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il y avait un échec de connection avec le service, réessayer à plus tard.
        /// </summary>
        public static string DlgServiceException {
            get {
                return ResourceManager.GetString("DlgServiceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les nombre de caractéres dans un nom d&apos;utilisateur est 30 comme maximum.
        /// </summary>
        public static string DlgUsernameMaxCharacters {
            get {
                return ResourceManager.GetString("DlgUsernameMaxCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom d&apos;utilisater est déjà enregistré.
        /// </summary>
        public static string DlgUsernameTaken {
            get {
                return ResourceManager.GetString("DlgUsernameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter nouvel ami.
        /// </summary>
        public static string LblAddNewFriend {
            get {
                return ResourceManager.GetString("LblAddNewFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En calculant des resultats....
        /// </summary>
        public static string LblCalculatingResults {
            get {
                return ResourceManager.GetString("LblCalculatingResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartes restantes.
        /// </summary>
        public static string LblCardsLeft {
            get {
                return ResourceManager.GetString("LblCardsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string LblChat {
            get {
                return ResourceManager.GetString("LblChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmer mot de passe.
        /// </summary>
        public static string LblConfirmPassword {
            get {
                return ResourceManager.GetString("LblConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courriel.
        /// </summary>
        public static string LblEmail {
            get {
                return ResourceManager.GetString("LblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration de jeu.
        /// </summary>
        public static string LblGameSettings {
            get {
                return ResourceManager.GetString("LblGameSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom temporel.
        /// </summary>
        public static string LblInGameUsername {
            get {
                return ResourceManager.GetString("LblInGameUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaderboard.
        /// </summary>
        public static string LblLeaderboard {
            get {
                return ResourceManager.GetString("LblLeaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeu fini.
        /// </summary>
        public static string LblMatchEnd {
            get {
                return ResourceManager.GetString("LblMatchEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string LblMyProfile {
            get {
                return ResourceManager.GetString("LblMyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code de groupe.
        /// </summary>
        public static string LblPartyCode {
            get {
                return ResourceManager.GetString("LblPartyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe.
        /// </summary>
        public static string LblPassword {
            get {
                return ResourceManager.GetString("LblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joueurs.
        /// </summary>
        public static string LblPlayers {
            get {
                return ResourceManager.GetString("LblPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prêt.
        /// </summary>
        public static string LblReady {
            get {
                return ResourceManager.GetString("LblReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom d&apos;utilisateur.
        /// </summary>
        public static string LblUsername {
            get {
                return ResourceManager.GetString("LblUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vainqueur.
        /// </summary>
        public static string LblWinner {
            get {
                return ResourceManager.GetString("LblWinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerte.
        /// </summary>
        public static string TitleAlert {
            get {
                return ResourceManager.GetString("TitleAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher.
        /// </summary>
        public static string TitleLauncher {
            get {
                return ResourceManager.GetString("TitleLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string TitleLogin {
            get {
                return ResourceManager.GetString("TitleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouvelle compte.
        /// </summary>
        public static string TitleNewAccount {
            get {
                return ResourceManager.GetString("TitleNewAccount", resourceCulture);
            }
        }
    }
}
